### ISSUE TITLE
Resources problems

### ISSUE THREAD

**Issue by imitoy** [AndroidIDE-CN/AIDEPlus#3]
I add this line to the `build.gradle` and meet this
```
implementation "com.google.android.material:material:1.12.0"
```
![Screenshot_2024_0824_183808](https://github.com/user-attachments/assets/758e540c-afb8-4d6a-9dca-cb65aacb6fa4)
It seems that the original build tool couldn't generate `R.java` because of these resources problems.
They should not exist.
Can you fix this?

**Comment by ZeroAicy** [comment]
> I add this line to the `build.gradle` and meet this
> 
> ```
> implementation "com.google.android.material:material:1.12.0"
> ```
> 
> ![Screenshot_2024_0824_183808](https://private-user-images.githubusercontent.com/173537881/361134472-758e540c-afb8-4d6a-9dca-cb65aacb6fa4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0OTk3OTAsIm5iZiI6MTcyNDQ5OTQ5MCwicGF0aCI6Ii8xNzM1Mzc4ODEvMzYxMTM0NDcyLTc1OGU1NDBjLWFmYjgtNGQ2YS05ZGNhLWNiNjVhYWNiNmZhNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNFQxMTM4MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMTdiYTEwNWY2NDMwYzljNDgwZDI5Y2Y5ZjFkZjhiNWI2M2Q2Mjc5ZjNkOTcxMWFkN2ExNzYyZGU4ZmRjODM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0sPj_44KG79UA8AYfduhZ4oKgqvPoztlzgObeWah1L0) It seems that the original build tool couldn't generate `R.java` because of these resources problems. They should not exist. Can you fix this?

This is not the fault of this project, is it

**Comment by imitoy** [comment]
oh...sorry.It's my fault
